// app/layout.tsx
import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import ModalProvider from '@/Providers/modalProvider'
import { TostProvider } from '@/Providers/TostProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className='max-w-[1366px] flex flex-col justify-center mx-auto'>
          <TostProvider />
          <ModalProvider />
          {children}
          </div>
          </body>
      </html>
    </ClerkProvider>
  )
}
